name: Render PlantUML Diagrams

on:
  push:
    branches:
      - main

jobs:
  generate_diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Diagrams from PlantUML
        run: |
          docker run --rm -v $(pwd):/workspace plantuml/plantuml -tsvg **/*.puml

      - name: Commit generated diagrams
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add **/*.svg
          git commit -m "Generated PlantUML diagrams"
          git push

